// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUiL8r8kPwgo5e4jGpYOnoiOrAnBVuJQ',
    appId: '1:512419182715:web:52e14178c8d6a334658ade',
    messagingSenderId: '512419182715',
    projectId: 'japser-code-challenge',
    authDomain: 'japser-code-challenge.firebaseapp.com',
    storageBucket: 'japser-code-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxnpcHTNeFn369lRbhHnDicwGCwUsxolg',
    appId: '1:512419182715:android:dfaaadab3bc46eb3658ade',
    messagingSenderId: '512419182715',
    projectId: 'japser-code-challenge',
    storageBucket: 'japser-code-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkLEp1PIXC61XQqrOXYWYsgxfaNi-ag0Q',
    appId: '1:512419182715:ios:7ef2379b9c20662a658ade',
    messagingSenderId: '512419182715',
    projectId: 'japser-code-challenge',
    storageBucket: 'japser-code-challenge.appspot.com',
    iosBundleId: 'com.example.jasperWeightTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkLEp1PIXC61XQqrOXYWYsgxfaNi-ag0Q',
    appId: '1:512419182715:ios:b366387f375a1cdd658ade',
    messagingSenderId: '512419182715',
    projectId: 'japser-code-challenge',
    storageBucket: 'japser-code-challenge.appspot.com',
    iosBundleId: 'com.example.jasperWeightTracker.RunnerTests',
  );
}
